// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btszrtpcgvkczrszdmyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c3pydHBjZ3ZrY3pyc3pkbXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3OTIyNTUsImV4cCI6MjA3OTM2ODI1NX0.CF4D52s6Cyl09RIztVKS7GLWi7BssneIs-DdUtUZgMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});